### ISSUE TITLE
Error runing

### ISSUE THREAD

**Issue by Aaryan9898** [lwzSoviet/NoXss#4]
Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead

**Comment by lwzSoviet** [comment]
> Message: unknown error: Chrome failed to start: exited abnormally.
> (unknown error: DevToolsActivePort file doesn't exist)
> (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
> 
> /usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead

It looks like your chrome is crashed? I'm not sure, you should install chrome and chromedriver correctly  before use this tool,Using "python start.py --check" to check this.
