### ISSUE TITLE
Error on raspberry pi 3 

### ISSUE THREAD

**Issue by spazbg** [lwzSoviet/NoXss#5]
![image](https://user-images.githubusercontent.com/22222777/92650220-e0761b00-f2f4-11ea-83b2-9965dda90963.png)

Any ideas on how to fix these errors?

**Comment by lwzSoviet** [comment]
This tool is running with python2.x not python3.x

**Comment by lwzSoviet** [comment]
> ![image](https://user-images.githubusercontent.com/22222777/92650220-e0761b00-f2f4-11ea-83b2-9965dda90963.png)
> 
> Any ideas on how to fix these errors?

This tool is running with python2.x not python3.x
