### ISSUE TITLE
Engine module is not found in pip2

### ISSUE THREAD

**Issue by swarupsro** [lwzSoviet/NoXss#6]
hello i am using `Kali Linux Rolling 2020.4`
i did everything according to the guideline but couldn't execute the project because of engine module.
here is the screenshot
![image](https://user-images.githubusercontent.com/7780919/101239084-fb4b0680-370e-11eb-8ad4-2e4698e1708f.png)

**Comment by lwzSoviet** [comment]
Did you execute "pip install -r requirements.txt"? it looks like the selenium package is not installed, you can execute "pip list | grep selenium" to check:
![20201214151034](https://user-images.githubusercontent.com/30397594/102051119-01cc3300-3e1f-11eb-8020-455ff269b027.png)
