### ISSUE TITLE
python3怎么用不了？ 很多包提示已过期

### ISSUE THREAD

**Issue by Yuri2** [lwzSoviet/NoXss#9]
python3怎么用不了？ 很多包提示已过期
'prettytable' version '0.7.2' is not installed (required: 0.7.2, installed: 2.0.0, latest: 2.1.0)
'gevent' version '1.4.0' is not installed (required: 1.4.0, installed: <nothing>, latest: 21.1.2)
'selenium' version '3.141.0' is not installed (required: 3.141.0, installed: <nothing>, latest: 3.141.0)
'beautifulsoup4' version '4.8.1' is not installed (required: 4.8.1, installed: 4.9.3, latest: 4.9.3)

**Comment by lwzSoviet** [comment]
It's based on python2.x
